{{- include "adp-helm-library.container-secret" (list . "adp-backstage-demo2.container-secret") -}}
{{- define "adp-backstage-demo2.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
{{- end -}}
